### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by haraun977** [venaxyt/Discord-ID-to-Token#2]
why only the first part i need the second part please im tryng to save my acc i got f2a locked out i need part 2

**Comment by Francesco2426** [comment]
> why only the first part i need the second part please im tryng to save my acc i got f2a locked out i need part 2

thats impossible lmao, just contact support

**Comment by 8nz** [comment]
> > why only the first part i need the second part please im tryng to save my acc i got f2a locked out i need part 2
> 
> thats impossible lmao, just contact support

support dont help for shit lol, already died w an old acc lmao

**Comment by venaxyt** [comment]
> > why only the first part i need the second part please im tryng to save my acc i got f2a locked out i need part 2
> 
> thats impossible lmao, just contact support

The second part is also possible to get, if I find again the script I used to do that, I will send it to you, but the third part is really impossible to get.

**Comment by venaxyt** [comment]
If you want to know, the second part represents the creation date of the account, you can get with the ID, I just don't remember how to "encrypt" it at the end :/

**Comment by 8nz** [comment]
> If you want to know, the second part represents the creation date of the account, you can get with the ID, I just don't remember how to "encrypt" it at the end :/


![image](https://user-images.githubusercontent.com/74454528/147112982-35937427-7e6e-4d92-8208-866995401788.png)

**Comment by venaxyt** [comment]
Exact, thanks for bring this shema here, it is very interesting x) !

**Comment by 6vh** [comment]
> Exact, thanks for bring this shema here, it is very interesting x) !

no problem, you should also maybe close this issue since its not really needed.

**Comment by venaxyt** [comment]
Yes, thanks bro x)
